export const actionTypes = {

    ADD_EMAIL: "ADD_EMAIL",

    SAVE_ANSWER: "SAVE_ANSWER",

    SHOW_ERROR: "SHOW_ERROR",

    SHOW_SUCCESS: "SHOW_SUCCESS",

    SHOW_ALERT: "SHOW_ALERT",

    HIDE_ALERT: "HIDE_ALERT",

    ADD_QUESTION: "ADD_QUESTION",

    ADD_GROUP: "ADD_GROUP",

    ADD_GROUP_QUESTION: "ADD_GROUP_QUESTION",

    REMOVE_QUESTION: "REMOVE_QUESTION",

    REMOVE_ALL: "REMOVE_ALL",


}

